#!/usr/bin/env python3
"""Emit LaTeX tables for the paper dataset section. Called from annotation_rounds_analysis.ipynb."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_PATH.parents[1]

LLM_CSV = PROJECT_ROOT / "data" / "labels" / "action_labels_llm_clean_refined.csv"
R001_MERGED = (
    PROJECT_ROOT
    / "data"
    / "annotation_rounds"
    / "r001_merged_validation"
    / "round1_validated_rows_with_decisions.csv"
)
R001_REFINED = (
    PROJECT_ROOT
    / "data"
    / "annotation_rounds"
    / "r001_gold_exports"
    / "r001_refined_combined"
    / "r001_refined_combined.csv"
)
R002_REFINED = (
    PROJECT_ROOT
    / "data"
    / "annotation_rounds"
    / "r002_gold_exports"
    / "r002_refined_combined"
    / "r002_refined_combined.csv"
)
GOLD_TRAIN = PROJECT_ROOT / "data" / "annotation_rounds" / "final_gold_dataset" / "train.csv"
GOLD_VAL = PROJECT_ROOT / "data" / "annotation_rounds" / "final_gold_dataset" / "val.csv"
GOLD_TEST = PROJECT_ROOT / "data" / "annotation_rounds" / "final_gold_dataset" / "test.csv"
OUT_TEX = PROJECT_ROOT / "doc" / "generated_paper_tables.tex"

PRIMARY_CLASSES = [
    "Object Transfer",
    "Essential Operation",
    "Stationary",
    "Locomotion",
    "Search",
]


def tex_num(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def tex_pct(x: float) -> str:
    return rf"{100 * x:.1f}\%"


def main() -> None:
    lines: list[str] = [
        "% Auto-generated by scripts/generate_paper_tables_tex.py",
        "% (invoked from notebooks/annotation_rounds_analysis.ipynb)",
        "% Do not edit by hand; regenerate from the notebook or: python scripts/generate_paper_tables_tex.py",
        "",
    ]

    df_llm = pd.read_csv(LLM_CSV, usecols=["scenario", "action", "video_uid"])
    mask5 = df_llm["action"].isin(PRIMARY_CLASSES)
    n_llm = int(mask5.sum())
    vc = df_llm.loc[mask5, "action"].value_counts()

    lines += [
        "% --- tab:action_dist_llm_full ---",
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        r"\caption{Action distribution, full LLM-labeled corpus (five primary classes; excludes Error/Invalid rows).}",
        r"\label{tab:action_dist_llm_full}",
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"Class & Count & \% \\",
        r"\midrule",
    ]
    for c in PRIMARY_CLASSES:
        cnt = int(vc.get(c, 0))
        lines.append(rf"{c} & {tex_num(cnt)} & {tex_pct(cnt / n_llm)} \\")
    lines += [
        r"\midrule",
        rf"Total & {tex_num(n_llm)} & {tex_pct(1.0)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]

    g = df_llm.loc[mask5].groupby("scenario").agg(
        narrations=("scenario", "size"),
        videos=("video_uid", pd.Series.nunique),
    )
    g = g.sort_values("narrations", ascending=False)
    total_n = int(g["narrations"].sum())
    v_unique_total = int(df_llm.loc[mask5, "video_uid"].nunique())

    lines += [
        "% --- tab:scenario_dist (LLM-labeled windows, five-class rows only) ---",
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        r"\caption{Scenario distribution: unique videos and narration windows in the LLM-labeled subset.}",
        r"\label{tab:scenario_dist}",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Scenario & Videos & Narrations & \% \\",
        r"\midrule",
    ]
    for scen, row in g.iterrows():
        nv = int(row["videos"])
        nn = int(row["narrations"])
        lines.append(rf"{scen} & {tex_num(nv)} & {tex_num(nn)} & {tex_pct(nn / total_n)} \\")
    lines += [
        r"\midrule",
        rf"Total & {tex_num(v_unique_total)} & {tex_num(total_n)} & {tex_pct(1.0)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]

    if R001_MERGED.is_file():
        r1 = pd.read_csv(R001_MERGED, usecols=["validated_final_verdict"])
        vc1 = r1["validated_final_verdict"].value_counts()
        tot1 = int(vc1.sum())
        lines += [
            "% --- tab:r1_verdict_dist ---",
            r"\begin{table}[ht]",
            r"\centering",
            r"\small",
            r"\caption{Round 1 validation verdict counts (merged export with validation columns).}",
            r"\label{tab:r1_verdict_dist}",
            r"\begin{tabular}{lrr}",
            r"\toprule",
            r"Verdict & Count & \% \\",
            r"\midrule",
        ]
        for v, cnt in vc1.items():
            lines.append(rf"{v} & {tex_num(int(cnt))} & {tex_pct(int(cnt) / tot1)} \\")
        lines += [
            r"\midrule",
            rf"Total & {tex_num(tot1)} & {tex_pct(1.0)} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]

    verdict_rows: list[tuple[str, pd.Series]] = []
    if R001_REFINED.is_file():
        a = pd.read_csv(R001_REFINED, usecols=["status_main"])
        verdict_rows.append(("r001 combined", a["status_main"].value_counts()))
    if R002_REFINED.is_file():
        b = pd.read_csv(R002_REFINED, usecols=["verdict"])
        verdict_rows.append(("r002 combined", b["verdict"].value_counts()))
    if verdict_rows:
        lines += [
            "% --- tab:refined_verdict_summary ---",
            r"\begin{table}[ht]",
            r"\centering",
            r"\small",
            r"\caption{Human validation verdict counts from refined combined exports (r001 and r002).}",
            r"\label{tab:refined_verdict_summary}",
            r"\begin{tabular}{llrr}",
            r"\toprule",
            r"Round & Verdict & Count & \% (within round) \\",
            r"\midrule",
        ]
        for i, (label, vc_) in enumerate(verdict_rows):
            t = int(vc_.sum())
            for v, cnt in vc_.items():
                lines.append(rf"{label} & {v} & {tex_num(int(cnt))} & {tex_pct(int(cnt) / t)} \\")
            if i < len(verdict_rows) - 1:
                lines.append(r"\midrule")
        lines += [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]

    motion_map = [
        ("Object Transfer", "Manipulation"),
        ("Essential Operation", "Manipulation"),
        ("Stationary", "Stationary"),
        ("Locomotion", "Locomotion"),
        ("Search", r"Search\_Interrupt"),
    ]
    lines += [
        "% --- tab:semantic_to_motion_map ---",
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        r"\caption{Mapping from five semantic classes to four IMU training classes.}",
        r"\label{tab:semantic_to_motion_map}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Semantic class & Motion class \\",
        r"\midrule",
    ]
    for sem, mot in motion_map:
        lines.append(rf"{sem} & {mot} \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]

    tr = pd.read_csv(GOLD_TRAIN, usecols=["action"])
    va = pd.read_csv(GOLD_VAL, usecols=["action"])
    te = pd.read_csv(GOLD_TEST, usecols=["action"])
    counts = {c: [0, 0, 0, 0] for c in PRIMARY_CLASSES}
    for c in PRIMARY_CLASSES:
        counts[c][0] = int((tr["action"] == c).sum())
        counts[c][1] = int((va["action"] == c).sum())
        counts[c][2] = int((te["action"] == c).sum())
        counts[c][3] = counts[c][0] + counts[c][1] + counts[c][2]
    n_all = sum(counts[c][3] for c in PRIMARY_CLASSES)

    lines += [
        "% --- tab:action_dist_gold ---",
        r"\begin{table}[ht]",
        r"\centering",
        r"\small",
        r"\caption{Action distribution on human-audited gold splits (five semantic classes).}",
        r"\label{tab:action_dist_gold}",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Class & Train & Val & Test & All & \% (All) \\",
        r"\midrule",
    ]
    for c in PRIMARY_CLASSES:
        t, v, s, a = counts[c]
        lines.append(rf"{c} & {tex_num(t)} & {tex_num(v)} & {tex_num(s)} & {tex_num(a)} & {tex_pct(a / n_all)} \\")
    lines += [
        r"\midrule",
        rf"Total & {tex_num(sum(counts[c][0] for c in PRIMARY_CLASSES))} & "
        rf"{tex_num(sum(counts[c][1] for c in PRIMARY_CLASSES))} & "
        rf"{tex_num(sum(counts[c][2] for c in PRIMARY_CLASSES))} & "
        rf"{tex_num(n_all)} & {tex_pct(1.0)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]

    tex = "\n".join(lines)
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(tex, encoding="utf-8")
    print(tex)
    print("\n--- written ---\n", OUT_TEX)


if __name__ == "__main__":
    main()
